---
# tasks file for anyenv
# - name: Run specified tasks on current platform
# include: "{{ ansible_os_family }}.yml"
- name: Check whether anyenv is installed
  stat: path="{{ anyenv_home }}/.anyenv"
  register: st_anyenv
  changed_when: no
- block:
  - name: Clone anyenv
    git: repo="https://github.com/riywo/anyenv" dest="{{ anyenv_home }}/.anyenv"
    become: yes
  - name: Set owner/group for anyenv
    file: >
      path="{{ anyenv_home }}/.anyenv"
      owner="{{ anyenv_owner }}"
      group="{{ anyenv_group }}"
      recurse=yes
    become: yes
  - name: Add profile settings for anyenv
    lineinfile: >
      dest="{{ anyenv_home }}/{{ anyenv_profile }}"
      line="{{ item }}"
      owner="{{ anyenv_owner }}"
      group="{{ anyenv_group }}"
      create=yes
    with_items:
      - "export PATH=\"$HOME/.anyenv/bin:$PATH\""
      - "eval \"$(anyenv init -)\""
    become: yes
  when: not st_anyenv.stat.exists
- name: Install rbenv
  shell: /bin/bash -lc "{{ anyenv_home }}/.anyenv/bin/anyenv install -s rbenv && {{ anyenv_home }}/.anyenv/envs/rbenv/bin/rbenv install -s 2.3.1 && {{ anyenv_home }}/.anyenv/envs/rbenv/bin/rbenv rehash && {{ anyenv_home }}/.anyenv/envs/rbenv/bin/rbenv global 2.3.1 && gem install bundler"
