---
- name: install bundler
  shell: >
    echo {{ dest }}
    gem install bundler
    chdir='{{ dest }}'
  become: no
- name: bundle install
  shell: >
    bundle install --jobs=4 --path=vendor/bundle --binstubs=vendor/bin --without doc test development --deployment
    chdir='{{ dest }}'
  environment: env
  become: no
  poll: 30
  async: 600

