---
- name: copy init script
  template:
    src=templates/init.j2
    dest=/etc/init.d/{{ project }}
    mode=755
  become: yes

- name: add start up
  command: update-rc.d {{ project }} defaults
  become: yes
