---
- name: install rpm packages
  apt: name={{item}} state=latest
  with_items:
    - g++
    - make
    - curl
    - zlib1g-dev
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libxml2-dev
    - libxslt-dev
    - sqlite3
    - sqlite3-dev
    - postgres-dev
    - redis-dev
- name: download ruby
  get_url: >
    url=http://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.gz
    dest=/tmp/ruby-2.3.1.tar.gz
- name: decomporess
  command: >
    tar xvzf ruby-2.3.1.tar.gz
    chdir=/tmp/
- name: configure
  command: >
    ./configure
    chdir=/tmp/ruby-2.3.1/
- name: make
  command: >
    make
    chdir=/tmp/ruby-2.3.1/
- name: make install
  command: >
    make install
    chdir=/tmp/ruby-2.3.1/