---
- name: install rpm packages
  apt: name={{item}} state=latest force=yes
  with_items:
    - g++
    - make
    - curl
    - zlib1g-dev
    - libssl-dev
    - libreadline-dev
    - libyaml-0-2
    - libyaml-dev
    - libxml2
    - libxml2-dev
    - libxslt-dev
    - sqlite3
    - libsqlite3-dev
    - imagemagick
    - libmagick++-dev
    - postgresql
    - postgresql-server-dev-9.3
  become: yes
  poll: 30
  async: 600
- name: decomporess
  unarchive: >
    src='http://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.gz'
    dest=/tmp/
    copy=no
- name: configure
  command: >
    ./configure --disable-install-rdoc
    chdir=/tmp/ruby-2.3.1/
- name: make
  command: >
    make
    chdir=/tmp/ruby-2.3.1/
  poll: 30
  async: 600
- name: make install
  command: >
    make install
    chdir=/tmp/ruby-2.3.1/
  become: yes
