---
- name: stop rails
  service:
    name={{ project }}
    state=stopped
  become: yes
  ignore_errors: yes

- name: start rails
  service:
    name={{ project }}
    state=started
  become: yes

- name: restart nginx
  service:
    name=nginx
    enabled=yes
    state=restarted
  become: yes
